import {StyleSheet} from 'react-native';
import {screenHeight, screenWidth} from '../../utils/dimensions';
import {hexToRgbA} from '../../utils/hexToRgba';
import {defaultTheme} from '../../config/theme';

export const createStyleSheet = () => {
  return StyleSheet.create({
    seperator: {
      borderBottomWidth: 1,
      borderBottomColor: hexToRgbA(defaultTheme.brown, 0.05),
      width: '100%',
      marginTop: 16,
      marginBottom: -8,
    },

    container: {
      backgroundColor: defaultTheme.white,
      paddingBottom: screenHeight / 3,
    },
    imageContainer: {
      position: 'relative',
    },
    profileImage: {
      width: '100%',
      borderBottomLeftRadius: 40,
      borderBottomRightRadius: 40,
    },
    imageProgressRow: {
      position: 'absolute',
      top: 12,
      left: 12,
      right: 12,
      flexDirection: 'row',
      gap: 6,
      zIndex: 2,
    },
    imageProgressBar: {
      flex: 1,
      height: 4,
      borderRadius: 999,
      backgroundColor: 'rgba(255,255,255,0.28)',
    },
    imageProgressBarActive: {
      backgroundColor: 'rgba(255,255,255,0.95)',
    },
    imageTapOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 120,
      flexDirection: 'row',
      zIndex: 1,
    },
    imageTapZone: {
      flex: 1,
    },
    backBtn: {
      position: 'absolute',
      top: 30,
      left: 20,
      backgroundColor: '#fff',
      borderRadius: 20,
      padding: 6,
    },
    actionButtons: {
      flexDirection: 'row',
      justifyContent: 'space-evenly',
      marginTop: -30,
    },
    circleButton: {
      width: 60,
      height: 60,
      backgroundColor: '#fff',
      borderRadius: 30,
      justifyContent: 'center',
      alignItems: 'center',
    },
    circleButtonBig: {
      width: 70,
      height: 70,
      backgroundColor: '#fff',
      borderRadius: 35,
      justifyContent: 'center',
      alignItems: 'center',
      borderColor: hexToRgbA('#000000', 6),
      borderWidth: 1,
    },
    profileInfo: {
      paddingHorizontal: 0,
      paddingTop: 0,
      marginTop: 0,
    },
    nameRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    name: {
      color: defaultTheme.darkText,
      fontSize: 16,
      lineHeight: 25,
      fontWeight: '500',
      flex: 1,
    },
    sectionTitle: {
      color: defaultTheme.mutedText,
      fontSize: 12,
      fontWeight: '500',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      marginBottom: 10,
    },
    aboutText: {
      color: defaultTheme.darkText,
      fontSize: 16,
      lineHeight: 25,
      fontWeight: '500',
    },
    interestsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: -2,
      marginBottom: -2,
    },
    interestPill: {
      borderRadius: 999,
      backgroundColor: defaultTheme.primaryDisabled,
      borderColor: hexToRgbA(defaultTheme.primary, 10),
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginRight: 8,
      marginBottom: 8,
    },
    interestText: {
      color: defaultTheme.primary,
      fontSize: 13,
      fontWeight: '500',
      letterSpacing: 0.2,
    },
    linearGradient: {
      flex: 1,
      paddingLeft: 15,
      paddingRight: 15,
      borderRadius: 5,
    },
    info: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 20,
      alignItems: 'flex-end',
      height: '100%',
      paddingBottom: 60,
    },
    more: {
      fontSize: 26,
      color: 'white',
    },
    likeUnlikeView: {
      backgroundColor: 'white',
      // flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    userDetailImageTop: {
      position: 'absolute',
      bottom: 0,
      paddingHorizontal: 16,
      paddingVertical: 50,
      left: 0,
      right: 0,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    userDetailImageTopText: {
      color: defaultTheme.cream,
      fontWeight: '500',
      fontSize: 30,
    },
    sectionCard: {
      borderRadius: 0,
      backgroundColor: '#ffffff',
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 0,
      borderColor: hexToRgbA(defaultTheme.primary, 10),
      borderTopWidth: 0,
      borderBottomWidth: 1,
      borderLeftWidth: 0,
      borderRightWidth: 0,
    },
    emptyCard: {
      borderRadius: 0,
      backgroundColor: '#ffffff',
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderColor: hexToRgbA(defaultTheme.primary, 10),
      borderTopWidth: 0,
      borderBottomWidth: 1,
      borderLeftWidth: 0,
      borderRightWidth: 0,
    },
    fullscreenOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 999,
      backgroundColor: 'rgba(0,0,0,0.4)', // optional: slight dim effect
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
};
