import { Platform, StyleSheet } from "react-native";
import { defaultTheme } from "../../config/theme";
import { hexToRgbA } from "../../utils/hexToRgba";

export const createStyleSheet = () => {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: "#ffffff",
    },
    profileShell: {
      flex: 1,
      backgroundColor: "#ffffff",
    },
    profileContent: {
      backgroundColor: "#ffffff",
      paddingHorizontal: 12,
      paddingTop: 6,
    },
    heroCard: {
      overflow: "hidden",
      borderRadius: 8,
      backgroundColor: "#f3f3f7",
      position: "relative",
    },
    heroImage: {
      width: "100%",
      backgroundColor: "#f3f3f7",
    },
    imageProgressRow: {
      position: "absolute",
      top: 12,
      left: 12,
      right: 12,
      flexDirection: "row",
      gap: 6,
      zIndex: 3,
    },
    imageProgressBar: {
      flex: 1,
      height: 3,
      borderRadius: 999,
      backgroundColor: "rgba(255,255,255,0.32)",
    },
    imageProgressBarActive: {
      backgroundColor: "rgba(255,255,255,0.95)",
    },
    imageTapOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 160,
      flexDirection: "row",
      zIndex: 2,
    },
    imageTapZone: {
      flex: 1,
    },
    heroOverlay: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      paddingHorizontal: 18,
      paddingTop: 92,
      paddingBottom: 24,
      zIndex: 4,
    },
    heroTextBlock: {
      gap: 4,
    },
    heroName: {
      color: "#ffffff",
      fontSize: 32,
      lineHeight: 38,
      fontWeight: "500",
    },
    heroMeta: {
      color: "rgba(255,255,255,0.82)",
      fontSize: 14,
      lineHeight: 20,
      fontWeight: "500",
    },
    promptCard: {
      marginTop: 10,
      borderRadius: 8,
      backgroundColor: "#f3f3f7",
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    promptLabel: {
      color: "#6b6b74",
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "500",
      marginBottom: 8,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    promptText: {
      color: "#171717",
      fontSize: 18,
      lineHeight: 26,
      fontWeight: "500",
    },
    bioCard: {
      marginTop: 10,
      borderRadius: 8,
      backgroundColor: "#f3f3f7",
      paddingHorizontal: 14,
      paddingVertical: 14,
      flexDirection: "row",
      gap: 12,
    },
    bioIconBubble: {
      width: 38,
      height: 38,
      borderRadius: 999,
      backgroundColor: "#ffffff",
      alignItems: "center",
      justifyContent: "center",
    },
    bioContent: {
      flex: 1,
    },
    bioLabel: {
      color: "#6b6b74",
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "500",
      marginBottom: 4,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    bioText: {
      color: "#171717",
      fontSize: 16,
      lineHeight: 23,
      fontWeight: "400",
    },
    sectionCard: {
      marginTop: 10,
      borderRadius: 8,
      backgroundColor: "#f3f3f7",
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    sectionTitle: {
      color: "#6b6b74",
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "500",
      marginBottom: 8,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    nameRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    name: {
      color: "#171717",
      fontSize: 18,
      lineHeight: 26,
      fontWeight: "500",
      flex: 1,
    },
    aboutText: {
      color: "#171717",
      fontSize: 18,
      lineHeight: 26,
      fontWeight: "500",
    },
    interestsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    interestPill: {
      borderRadius: 999,
      backgroundColor: "#ffffff",
      borderWidth: 1,
      borderColor: "#e4e4ea",
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    interestText: {
      color: defaultTheme.primary,
      fontSize: 13,
      lineHeight: 17,
      fontWeight: "500",
    },
    chipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    chip: {
      borderRadius: 999,
      backgroundColor: "#ffffff",
      borderWidth: 1,
      borderColor: "#e4e4ea",
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    chipText: {
      color: defaultTheme.primary,
      fontSize: 13,
      lineHeight: 17,
      fontWeight: "500",
    },
    stickyActions: {
      position: "absolute",
      left: 28,
      right: 28,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      zIndex: 20,
      pointerEvents: "box-none",
    },
    actionButton: {
      width: 64,
      height: 64,
      borderRadius: 999,
      backgroundColor: "#ffffff",
      borderWidth: 1,
      borderColor: "#e7e7ec",
      alignItems: "center",
      justifyContent: "center",
      ...(Platform.OS === "web" ? ({ cursor: "pointer" } as object) : null),
    },
    likeButton: {
      width: 64,
      height: 64,
    },
    permissionScreen: {
      flex: 1,
      backgroundColor: "#ffffff",
      paddingHorizontal: 16,
      paddingTop: 18,
    },
    permissionTitle: {
      marginTop: 18,
      color: "#161616",
      fontSize: 40 / 1.5,
      lineHeight: 56 / 1.5,
      fontWeight: "500",
    },
    permissionText: {
      marginTop: 8,
      color: "#60606a",
      fontSize: 16,
      lineHeight: 24,
      fontWeight: "500",
      maxWidth: 330,
    },
    permissionHint: {
      marginTop: 10,
      color: "#7a7a84",
      fontSize: 13,
      lineHeight: 19,
      fontWeight: "500",
      maxWidth: 340,
    },
    permissionButton: {
      marginTop: 24,
    },
    noNearbyScreen: {
      flex: 1,
      backgroundColor: "#ffffff",
      paddingHorizontal: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    noNearbyBadge: {
      width: 54,
      height: 54,
      borderRadius: 18,
      backgroundColor: "#f3f3f7",
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 14,
    },
    noNearbyText: {
      color: "#5d5d66",
      fontSize: 16,
      lineHeight: 24,
      fontWeight: "500",
      textAlign: "center",
    },
    fullscreenOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 999,
      backgroundColor: hexToRgbA("#ffffff", 88),
      alignItems: "center",
      justifyContent: "center",
    },
  });
};
