import {StyleSheet} from 'react-native';
import {defaultTheme} from '../../config/theme';

export const createStyleSheet = () => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: defaultTheme.pinkSurface,
    },
    scrollView: {
      flex: 1,
    },
    content: {
      paddingBottom: 24,
      paddingTop: 0,
    },
    contentInner: {
      width: '100%',
      paddingHorizontal: 0,
    },
    imageWrap: {
      position: 'relative',
      marginTop: 0,
      borderRadius: 0,
      overflow: 'hidden',
      backgroundColor: '#f3d8e1',
      shadowColor: '#0f172a',
      shadowOffset: {width: 0, height: 0},
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    image: {
      width: '100%',
    },
    imageOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
    },
    heroTopRow: {
      position: 'absolute',
      top: 14,
      left: 14,
      right: 14,
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    likedBadge: {
      backgroundColor: 'rgba(255,255,255,0.95)',
      borderRadius: 999,
      paddingVertical: 7,
      paddingHorizontal: 12,
    },
    likedBadgeText: {
      color: defaultTheme.pinkText,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    overlayContent: {
      position: 'absolute',
      left: 14,
      right: 14,
      bottom: 14,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    overlayTitle: {
      color: '#ffffff',
      fontWeight: '700',
      fontSize: 33,
      lineHeight: 39,
      flex: 1,
      textShadowColor: 'rgba(0,0,0,0.24)',
      textShadowOffset: {width: 0, height: 2},
      textShadowRadius: 8,
    },
    agePill: {
      backgroundColor: 'rgba(249, 97, 99, 0.28)',
      borderColor: 'rgba(255,255,255,0.4)',
      borderWidth: 1,
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 12,
      minWidth: 42,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ageText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '700',
    },
    locationPill: {
      marginTop: 9,
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(161, 36, 87, 0.42)',
      borderRadius: 999,
      paddingVertical: 7,
      paddingHorizontal: 11,
    },
    locationText: {
      color: '#ffffff',
      fontSize: 13,
      fontWeight: '600',
    },
    profileInfo: {
      marginTop: 0,
      marginBottom: 0,
    },
    sectionCard: {
      borderRadius: 0,
      backgroundColor: '#ffffff',
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 0,
      borderColor: defaultTheme.pinkBorder,
      borderTopWidth: 0,
      borderBottomWidth: 1,
      borderLeftWidth: 0,
      borderRightWidth: 0,
      shadowColor: '#0f172a',
      shadowOffset: {width: 0, height: 0},
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    sectionTitle: {
      color: defaultTheme.mutedText,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      marginBottom: 10,
    },
    sectionBody: {
      color: defaultTheme.darkText,
      fontSize: 16,
      lineHeight: 25,
      fontWeight: '500',
    },
    chipsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: -2,
      marginBottom: -2,
    },
    infoChip: {
      borderRadius: 999,
      backgroundColor: '#fff0f5',
      borderColor: defaultTheme.pinkBorder,
      borderWidth: 1,
      paddingVertical: 8,
      paddingHorizontal: 12,
      marginRight: 8,
      marginBottom: 8,
    },
    infoChipText: {
      color: defaultTheme.pinkText,
      fontSize: 13,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    emptyCard: {
      borderRadius: 0,
      backgroundColor: '#ffffff',
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderColor: defaultTheme.pinkBorder,
      borderTopWidth: 0,
      borderBottomWidth: 1,
      borderLeftWidth: 0,
      borderRightWidth: 0,
    },
    stickyActionBar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      paddingTop: 10,
      paddingHorizontal: 12,
      borderTopWidth: 1,
      borderTopColor: defaultTheme.pinkBorder,
      backgroundColor: 'rgba(255,255,255,0.97)',
    },
    stickyActionInner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    actionButton: {
      flex: 1,
      borderRadius: 14,
      minHeight: 50,
      paddingHorizontal: 12,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    actionButtonDisabled: {
      opacity: 0.6,
    },
    dislikeButton: {
      backgroundColor: '#fff6f9',
      borderColor: defaultTheme.pinkBorder,
      borderWidth: 1,
    },
    dislikeButtonActive: {
      borderColor: defaultTheme.pinkPrimary,
      backgroundColor: '#ffe9f0',
    },
    dislikeButtonText: {
      color: defaultTheme.pinkText,
      fontSize: 15,
      fontWeight: '700',
    },
    likeButton: {
      backgroundColor: defaultTheme.pinkPrimary,
    },
    likeButtonActive: {
      backgroundColor: defaultTheme.pinkSecondary,
    },
    likeButtonText: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: '700',
    },
  });
};
