import { StyleSheet } from "react-native";
import { defaultTheme } from "../../config/theme";
import { hexToRgbA } from "../../utils/hexToRgba";

export const createStyleSheet = () =>
  StyleSheet.create({
    wrapper: {
      flex: 1,
      backgroundColor: defaultTheme.white,
    },
    keyboardLayout: {
      flex: 1,
      backgroundColor: defaultTheme.white,
    },
    keyboardScrollContent: {
      flexGrow: 1,
    },
    keyboardContent: {
      flexGrow: 1,
    },
    keyboardFooter: {
      backgroundColor: defaultTheme.white,
    },
    background: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 8,
      backgroundColor: defaultTheme.white,
      position: "relative",
    },
    progressHeader: {
      marginBottom: 10,
    },
    stepText: {
      fontSize: 13,
      color: defaultTheme.primary,
      fontWeight: "500",
      marginBottom: 8,
    },
    progressTrack: {
      width: "100%",
      height: 8,
      borderRadius: 999,
      backgroundColor: defaultTheme.primaryDisabled,
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      borderRadius: 999,
      backgroundColor: defaultTheme.primary,
    },
    container: {
      // borderRadius: 24,
      // borderWidth: 1,
      // borderColor: defaultTheme.pinkBorder,
      // backgroundColor: "#ffffff",
      // paddingBottom: 20,
      minHeight: 330,
    },
    cardTopRow: {
      minHeight: 30,
      marginBottom: 6,
      justifyContent: "center",
    },
    inlineBackPlaceholder: {
      height: 30,
    },
    inlineBackBtn: {
      alignSelf: "flex-start",
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      paddingVertical: 12,
    },
    inlineBackLabel: {
      fontSize: 14,
      fontWeight: "500",
      color: defaultTheme.primary,
    },
    title: {
      fontSize: 28,
      lineHeight: 34,
      color: defaultTheme.darkText,
      fontWeight: "500",
      marginBottom: 6,
    },
    subtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: hexToRgbA(defaultTheme.primary, 60),
      marginBottom: 18,
      fontWeight: "500",
    },
    fieldBlock: {
      gap: 12,
    },
    datePickerTrigger: {
      position: "relative",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: defaultTheme.pinkBorder,
      backgroundColor: "#fff5f9",
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 6,
    },
    datePickerLabel: {
      fontSize: 12,
      color: defaultTheme.mutedText,
      fontWeight: "500",
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    datePickerValueRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    datePickerValueText: {
      fontSize: 15,
      color: defaultTheme.darkText,
      fontWeight: "500",
      flex: 1,
    },
    chipContainer: {
      flexWrap: "wrap",
      flexDirection: "row",
      gap: 10,
    },
    photoGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    photoCard: {
      width: "48%",
      aspectRatio: 1.08,
      borderRadius: 18,
      overflow: "hidden",
      backgroundColor: defaultTheme.primaryDisabled,
      borderWidth: 1,
      borderColor: defaultTheme.primaryDisabled,
      position: "relative",
    },
    photoCardFilled: {
      backgroundColor: defaultTheme.primaryDisabled,
      borderColor: defaultTheme.primary,
    },
    photoPreview: {
      width: "100%",
      height: "100%",
    },
    photoPlaceholder: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 12,
      gap: 8,
    },
    photoPlusIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: defaultTheme.white,
    },
    photoPlaceholderTitle: {
      fontSize: 13,
      lineHeight: 16,
      color: defaultTheme.primary,
      fontWeight: "500",
      textAlign: "center",
    },
    photoPlaceholderText: {
      fontSize: 11,
      lineHeight: 14,
      color: hexToRgbA(defaultTheme.primary, 62),
      fontWeight: "500",
      textAlign: "center",
    },
    removePhotoButton: {
      position: "absolute",
      top: 10,
      right: 10,
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(17,17,17,0.72)",
    },
    photoTipsCard: {
      marginTop: 4,
      borderRadius: 16,
      backgroundColor: defaultTheme.primaryDisabled,
      borderWidth: 1,
      borderColor: defaultTheme.primaryDisabled,
      paddingHorizontal: 12,
      paddingVertical: 12,
      gap: 8,
    },
    photoTipsTitle: {
      fontSize: 13,
      lineHeight: 16,
      color: defaultTheme.primary,
      fontWeight: "500",
    },
    photoTipRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 8,
    },
    photoTipDot: {
      width: 6,
      height: 6,
      borderRadius: 999,
      marginTop: 5,
      backgroundColor: defaultTheme.primary,
    },
    photoTipText: {
      flex: 1,
      fontSize: 12,
      lineHeight: 16,
      color: hexToRgbA(defaultTheme.primary, 72),
      fontWeight: "500",
    },
    continueButton: {
      marginTop: 0,
    },
    submitErrorText: {
      marginTop: 8,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: "500",
      color: "#b91c1c",
      paddingHorizontal: 4,
    },
    dateDoneButton: {
      alignSelf: "flex-start",
      marginTop: 6,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: "#fff3f7",
      borderWidth: 1,
      borderColor: defaultTheme.pinkBorder,
    },
    dateDoneButtonText: {
      color: defaultTheme.pinkText,
      fontSize: 12,
      fontWeight: "500",
    },
    labelStyle: {
      fontSize: 14,
      fontWeight: "500",
      color: defaultTheme.darkText,
    },
    successOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(255, 247, 250, 0.92)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
      zIndex: 50,
    },
    successCard: {
      width: "100%",
      maxWidth: 360,
      borderRadius: 20,
      backgroundColor: "#ffffff",
      borderColor: defaultTheme.pinkBorder,
      borderWidth: 1,
      paddingHorizontal: 20,
      paddingVertical: 24,
      alignItems: "center",
      gap: 8,
    },
    successTitle: {
      marginTop: 2,
      fontSize: 24,
      fontWeight: "500",
      color: defaultTheme.darkText,
    },
    successSubtitle: {
      fontSize: 14,
      color: defaultTheme.mutedText,
      fontWeight: "500",
    },
  });
