import {StyleSheet} from 'react-native';
import {defaultTheme} from '../../config/theme';
import {hexToRgbA} from '../../utils/hexToRgba';

export const createStyleSheet = () =>
  StyleSheet.create({
    wrapper: {
      flex: 1,
      backgroundColor: defaultTheme.pinkSurface,
    },
    background: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
      backgroundColor: defaultTheme.pinkSurface,
      position: 'relative',
    },
    progressHeader: {
      marginBottom: 10,
    },
    stepText: {
      fontSize: 13,
      color: defaultTheme.mutedText,
      fontWeight: '600',
      marginBottom: 8,
    },
    progressTrack: {
      width: '100%',
      height: 8,
      borderRadius: 999,
      backgroundColor: defaultTheme.pinkBorder,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 999,
      backgroundColor: defaultTheme.pinkPrimary,
    },
    container: {
      borderRadius: 24,
      borderWidth: 1,
      borderColor: defaultTheme.pinkBorder,
      backgroundColor: '#ffffff',
      paddingHorizontal: 18,
      paddingTop: 18,
      paddingBottom: 20,
      minHeight: 330,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 12},
      shadowOpacity: 0.07,
      shadowRadius: 20,
      elevation: 4,
    },
    cardTopRow: {
      minHeight: 30,
      marginBottom: 6,
      justifyContent: 'center',
    },
    inlineBackPlaceholder: {
      height: 30,
    },
    inlineBackBtn: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
      paddingVertical: 2,
      paddingHorizontal: 2,
    },
    inlineBackLabel: {
      fontSize: 14,
      fontWeight: '700',
      color: hexToRgbA(defaultTheme.darkText, 0.7),
    },
    title: {
      fontSize: 28,
      lineHeight: 34,
      color: defaultTheme.darkText,
      fontWeight: '700',
      marginBottom: 6,
    },
    subtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: defaultTheme.mutedText,
      marginBottom: 18,
      fontWeight: '500',
    },
    fieldBlock: {
      gap: 12,
    },
    datePickerTrigger: {
      position: 'relative',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: defaultTheme.pinkBorder,
      backgroundColor: '#fff5f9',
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 6,
    },
    datePickerLabel: {
      fontSize: 12,
      color: defaultTheme.mutedText,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    datePickerValueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    datePickerValueText: {
      fontSize: 15,
      color: defaultTheme.darkText,
      fontWeight: '600',
      flex: 1,
    },
    chipContainer: {
      flexWrap: 'wrap',
      flexDirection: 'row',
      gap: 10,
    },
    continueButton: {
      marginTop: 18,
      borderRadius: 14,
    },
    submitErrorText: {
      marginTop: 8,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
      color: '#b91c1c',
      paddingHorizontal: 4,
    },
    dateDoneButton: {
      alignSelf: 'flex-start',
      marginTop: 6,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
      backgroundColor: '#fff3f7',
      borderWidth: 1,
      borderColor: defaultTheme.pinkBorder,
    },
    dateDoneButtonText: {
      color: defaultTheme.pinkText,
      fontSize: 12,
      fontWeight: '700',
    },
    labelStyle: {
      fontSize: 14,
      fontWeight: '600',
      color: defaultTheme.darkText,
    },
    successOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(255, 247, 250, 0.92)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
      zIndex: 50,
    },
    successCard: {
      width: '100%',
      maxWidth: 360,
      borderRadius: 20,
      backgroundColor: '#ffffff',
      borderColor: defaultTheme.pinkBorder,
      borderWidth: 1,
      paddingHorizontal: 20,
      paddingVertical: 24,
      alignItems: 'center',
      gap: 8,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.14,
      shadowRadius: 18,
      elevation: 8,
    },
    successTitle: {
      marginTop: 2,
      fontSize: 24,
      fontWeight: '700',
      color: defaultTheme.darkText,
    },
    successSubtitle: {
      fontSize: 14,
      color: defaultTheme.mutedText,
      fontWeight: '600',
    },
  });
